tide_chruby_bg_color normal
tide_chruby_color $_chruby
tide_cmd_duration_bg_color normal
tide_cmd_duration_color $_dark_yellowish_gray
tide_context_bg_color normal
tide_git_bg_color normal
tide_git_bg_color_unstable normal
tide_git_bg_color_urgent normal
tide_git_color_branch $_light_green
tide_git_color_conflicted $_light_red
tide_git_color_dirty $_gold
tide_git_color_operation $_light_red
tide_git_color_staged $_gold
tide_git_color_stash $_light_green
tide_git_color_untracked $_light_blue
tide_git_color_upstream $_light_green
tide_go_bg_color normal
tide_go_color $_go
tide_jobs_bg_color normal
tide_jobs_color $_green
tide_kubectl_bg_color normal
tide_kubectl_color $_kubectl
tide_left_prompt_frame_enabled false
tide_left_prompt_items pwd git newline character
tide_left_prompt_separator_diff_color ' '
tide_left_prompt_separator_same_color ' '
tide_left_prompt_suffix ' '
tide_node_bg_color normal
tide_node_color $_node
tide_os_bg_color normal
tide_os_color $_subtle_offwhite
tide_php_bg_color normal
tide_php_color $_php
tide_private_mode_bg_color normal
tide_private_mode_color $_pure_white
tide_prompt_pad_items false
tide_pwd_bg_color normal
tide_pwd_color_anchors $_light_blue
tide_pwd_color_dirs $_dark_blue
tide_pwd_color_truncated_dirs $_violet
tide_right_prompt_frame_enabled false
tide_right_prompt_prefix ' '
tide_right_prompt_separator_diff_color ' '
tide_right_prompt_separator_same_color ' '
tide_rustc_bg_color normal
tide_rustc_color $_rustc
tide_shlvl_bg_color normal
tide_shlvl_color $_shlvl
tide_status_bg_color normal
tide_status_bg_color_failure normal
tide_status_color_failure $_slightly_dark_red
tide_terraform_bg_color normal
tide_terraform_color $_terraform
tide_time_bg_color normal
tide_time_color $_bluish_grayish
tide_toolbox_bg_color normal
tide_toolbox_color $_toolbox
tide_vi_mode_bg_color_default
tide_vi_mode_bg_color_replace
tide_vi_mode_bg_color_visual
tide_vi_mode_color_default
tide_vi_mode_color_replace
tide_vi_mode_color_visual
tide_vi_mode_icon_default
tide_vi_mode_icon_replace
tide_vi_mode_icon_visual
tide_virtual_env_bg_color normal
tide_virtual_env_color $_virtual_env
