tide_character_bg_color normal
tide_character_color_failure FF0000
tide_character_color_success $_tide_color_green
tide_character_icon '❯'
tide_character_vi_icon_default '❮'
tide_character_vi_icon_insert '❯'
tide_character_vi_icon_replace '▶'
tide_character_vi_icon_visual V
tide_chruby_bg_color normal
tide_chruby_color CC342D
tide_chruby_icon ''
tide_cmd_duration_bg_color normal
tide_cmd_duration_color 87875F
tide_cmd_duration_decimals 0
tide_cmd_duration_icon
tide_cmd_duration_threshold 3000
tide_context_always_display false
tide_context_bg_color normal
tide_context_color_default D7AF87
tide_context_color_root_color $_tide_color_gold
tide_context_color_ssh D7AF87
tide_git_bg_color normal
tide_git_color_branch $_tide_color_green
tide_git_color_conflicted FF0000
tide_git_color_dirty $_tide_color_gold
tide_git_color_operation FF0000
tide_git_color_staged $_tide_color_gold
tide_git_color_stash $_tide_color_green
tide_git_color_untracked $_tide_color_light_blue
tide_git_color_upstream $_tide_color_green
tide_git_icon
tide_jobs_bg_color normal
tide_jobs_color $_tide_color_dark_green
tide_jobs_icon ''
tide_left_prompt_frame_enabled false
tide_left_prompt_items pwd git newline character
tide_left_prompt_prefix ''
tide_left_prompt_separator_diff_color ' '
tide_left_prompt_separator_same_color ' '
tide_left_prompt_suffix ' '
tide_nvm_bg_color normal
tide_nvm_color 00AFAF
tide_nvm_default_node
tide_nvm_icon '⬢'
tide_os_bg_color normal
tide_os_color normal
tide_php_bg_color normal
tide_php_color 875FFF
tide_php_icon ''
tide_prompt_add_newline_before true
tide_prompt_color_frame_and_connection 6C6C6C
tide_prompt_color_separator_same_color 949494
tide_prompt_icon_connection ' '
tide_prompt_pad_items false
tide_pwd_bg_color normal
tide_pwd_color_anchors $_tide_color_light_blue
tide_pwd_color_dirs $_tide_color_dark_blue
tide_pwd_color_truncated_dirs 8787AF
tide_pwd_icon_dir
tide_pwd_icon_home
tide_pwd_icon_unwritable ''
tide_pwd_markers .bzr .citc .git .hg .node-version .python-version .ruby-version .shorten_folder_marker .svn .terraform Cargo.toml composer.json CVS go.mod package.json
tide_right_prompt_frame_enabled false
tide_right_prompt_items status cmd_duration context jobs nvm virtual_env rustc php chruby
tide_right_prompt_prefix ' '
tide_right_prompt_separator_diff_color ' '
tide_right_prompt_separator_same_color ' '
tide_right_prompt_suffix ''
tide_rustc_bg_color normal
tide_rustc_color 00AFAF
tide_rustc_icon ''
tide_shlvl_bg_color normal
tide_shlvl_color d78700
tide_shlvl_icon '↕️'
tide_shlvl_threshold 1
tide_status_bg_color_failure normal
tide_status_bg_color_success normal
tide_status_color_failure D70000
tide_status_color_success $_tide_color_dark_green
tide_status_icon_failure '✘'
tide_status_icon_success '✔'
tide_time_bg_color normal
tide_time_color 5F8787
tide_time_format '%T'
tide_vi_mode_bg_color_default
tide_vi_mode_bg_color_insert
tide_vi_mode_bg_color_replace
tide_vi_mode_bg_color_visual
tide_vi_mode_color_default
tide_vi_mode_color_replace
tide_vi_mode_color_visual
tide_vi_mode_icon_default
tide_vi_mode_icon_replace
tide_vi_mode_icon_visual
tide_virtual_env_bg_color normal
tide_virtual_env_color 00AFAF
tide_virtual_env_display_mode projectName
tide_virtual_env_icon ''
