__fish_git_prompt_char_cleanstate ''
__fish_git_prompt_char_dirtystate ' !'
__fish_git_prompt_char_stagedstate ' +'
__fish_git_prompt_char_stashstate ' *'
__fish_git_prompt_char_stateseparator ''
__fish_git_prompt_char_untrackedfiles ' ?'
__fish_git_prompt_char_upstream_ahead ' ⇡'
__fish_git_prompt_char_upstream_behind ' ⇣'
__fish_git_prompt_color_branch 000000
__fish_git_prompt_color_dirtystate 000000
__fish_git_prompt_color_stagedstate 000000
__fish_git_prompt_color_stashstate 000000
__fish_git_prompt_color_untrackedfiles 000000
__fish_git_prompt_color_upstream 000000
__fish_git_prompt_show_informative_status true
__fish_git_prompt_showstashstate true
tide_cmd_duration_bg_color C4A000
tide_cmd_duration_color 000000
tide_cmd_duration_decimals 0
tide_cmd_duration_threshold 3000
tide_context_always_display false
tide_context_bg_color 444444
tide_context_default_color D7AF87
tide_context_root_color $_tide_color_gold
tide_context_ssh_color D7AF87
tide_git_prompt_bg_color 4E9A06
tide_jobs_bg_color 444444
tide_jobs_color 4E9A06
tide_jobs_icon ''
tide_left_prompt_frame_color 6C6C6C
tide_left_prompt_frame_enabled true
tide_left_prompt_item_separator_diff_color ''
tide_left_prompt_item_separator_same_color ''
tide_left_prompt_item_separator_same_color_color 949494
tide_left_prompt_items 'pwd' 'git_prompt' 'newline'
tide_left_prompt_pad_items true
tide_left_prompt_prefix ''
tide_left_prompt_suffix ''
tide_nvm_bg_color 75507B
tide_nvm_color 2E3436
tide_nvm_default_node
tide_nvm_icon '⬢'
tide_os_bg_color CED7CF
tide_os_color 080808
tide_print_newline_before_prompt 'true'
tide_prompt_char_bg_color normal
tide_prompt_char_failure_color FF0000
tide_prompt_char_icon '❯'
tide_prompt_char_success_color $_tide_color_green
tide_prompt_char_vi_default_icon '❮'
tide_prompt_char_vi_insert_icon '❯'
tide_prompt_char_vi_replace_icon '▶'
tide_prompt_char_vi_visual_icon 'V'
tide_prompt_connection_color 6C6C6C
tide_prompt_connection_icon ''
tide_pwd_anchors 'first' 'last' 'git'
tide_pwd_bg_color blue
tide_pwd_color_anchors E4E4E4
tide_pwd_color_dirs E4E4E4
tide_pwd_color_truncated_dirs BCBCBC
tide_pwd_dir_icon
tide_pwd_home_icon
tide_pwd_max_dirs 0
tide_pwd_truncate_margin 10
tide_pwd_unwritable_icon ''
tide_right_prompt_frame_color 6C6C6C
tide_right_prompt_frame_enabled true
tide_right_prompt_item_separator_diff_color ''
tide_right_prompt_item_separator_same_color ''
tide_right_prompt_item_separator_same_color_color 949494
tide_right_prompt_items 'status' 'cmd_duration' 'context' 'jobs' 'nvm' 'virtual_env' 'vi_mode'
tide_right_prompt_pad_items true
tide_right_prompt_prefix ''
tide_right_prompt_suffix ''
tide_rust_bg_color FF8700
tide_rust_color 2E3436
tide_rust_icon ''
tide_rust_verbose_version true
tide_status_always_display false
tide_status_failure_bg_color CC0000
tide_status_failure_color FFFF00
tide_status_failure_icon '✘'
tide_status_success_bg_color 2E3436
tide_status_success_color 4E9A06
tide_status_success_icon '✔'
tide_time_bg_color D3D7CF
tide_time_color 000000
tide_time_format '%T'
tide_vi_mode_default_bg_color 008000
tide_vi_mode_default_color 000000
tide_vi_mode_default_icon DEFAULT
tide_vi_mode_insert_bg_color 444444
tide_vi_mode_insert_color
tide_vi_mode_insert_icon
tide_vi_mode_replace_bg_color 808000
tide_vi_mode_replace_color 000000
tide_vi_mode_replace_icon REPLACE
tide_vi_mode_visual_bg_color 000080
tide_vi_mode_visual_color 000000
tide_vi_mode_visual_icon VISUAL
tide_virtual_env_bg_color 444444
tide_virtual_env_color 00AFAF
tide_virtual_env_display_mode 'projectName'
tide_virtual_env_icon ''